[package]
name = "boojieq/head-converter"
description = "Library for converting between classic and dynamic heads on avatars"
version = "1.0.2"
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
license = "MIT"
include = [
    "default.project.json",
    "src",
    "wally.toml",
    "README.md",
    "LICENSE"
]

[dependencies]
Promise = "maximumadhd/promise-typed@1.0.0"